### ISSUE TITLE
Installation and Running instructions are mixed together

### ISSUE THREAD

**Issue by jbrucker** [llleyelll/django-polls#1]
You have included installation instructions in your README,
including how to install dependencies.

That is good, but it will be much clearer if you separate
them into "Installation" and "Running".
In the "Installation", don't forget to run database migrations.

**Comment by chiiida** [comment]
I have updated and separated them into the "Installation" and "Running" part in README already.
Thank you for pointing me out a mistake. That is very helpful. 🍡🙏
